name: Update Data

on:
  push:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:
concurrency: 
  group: update-data
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Grab API, parse, and change files to new data
        uses: ThatTimothy/api-grabber@v1.0.0
        with:
          options: "options.json"
      
      - name: Commit changes
        run: |
          git config user.name Data_Updater
          git config user.email github-actions@github.com
          git add .
          git commit -m "`date -u +'%H:%M:%S %Y-%m-%d'`"
      
      - name: Pull new changes (if we can)
        run: |
          git pull
      
      - name: Push changes
        run: |
          git push
          
      - name: Start next action
        if: always() #Prevent an error from stopping next action
        run: |
          curl \
           -X POST \
           -H "Authorization: token ${{ secrets.PAT }}" \
           -H "Accept: application/vnd.github.v3+json" \
           https://api.github.com/repos/ThatTimothy/live-stats/actions/workflows/7000478/dispatches \
           -d '{"ref":"${{ github.ref }}"}'
